# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runpod < Formula
  desc ""
  homepage "https://github.com/runpod/runpodctl"
  version "1.14.2"

  on_macos do
    url "https://github.com/runpod/runpodctl/releases/download/v1.14.2/runpodctl_1.14.2_darwin_all.tar.gz"
    sha256 "60b63b763342a8ab8032332a32bfd8811fed0db99ca73f08f4d7c2bc11e59380"

    def install
      bin.install "runpodctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runpod/runpodctl/releases/download/v1.14.2/runpodctl_1.14.2_linux_arm64.tar.gz"
      sha256 "2f11e49e5ba930a3c1f8317f4e2183fc93e208fe07ecda80d81964d3b984816d"

      def install
        bin.install "runpodctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runpod/runpodctl/releases/download/v1.14.2/runpodctl_1.14.2_linux_amd64.tar.gz"
      sha256 "d1481f75a3ecab670e17679eed1bc0b321f56f9d2f5f65e436485af150199a04"

      def install
        bin.install "runpodctl"
      end
    end
  end
end
