# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runpod < Formula
  desc ""
  homepage "https://github.com/runpod/runpodctl"
  version "1.14.3"

  on_macos do
    url "https://github.com/runpod/runpodctl/releases/download/v1.14.3/runpodctl_1.14.3_darwin_all.tar.gz"
    sha256 "6fec45133e66baa7e48f8f15875c5a08c39b500444acda8e24be49e708467af3"

    def install
      bin.install "runpodctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runpod/runpodctl/releases/download/v1.14.3/runpodctl_1.14.3_linux_arm64.tar.gz"
      sha256 "2643efc293a00f8cc460240da441ceaab76b5c720735259a3599caa6b215b121"

      def install
        bin.install "runpod"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runpod/runpodctl/releases/download/v1.14.3/runpodctl_1.14.3_linux_amd64.tar.gz"
      sha256 "9b3f8ab13e0cd464e4506c1a0ee458acd1c97a2ca747bf7a3d3fd6b0a9829cb5"

      def install
        bin.install "runpod"
      end
    end
  end
end
