# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runpodctl < Formula
  desc ""
  homepage "https://github.com/runpod/runpodctl"
  version "1.14.3"

  on_macos do
    url "https://github.com/runpod/runpodctl/releases/download/v1.14.3/runpodctl_1.14.3_darwin_all.tar.gz"
    sha256 "48e67d78311ef5e0b7a24b57a4e402b3a17543cee5ac37bff6c20a86264338f7"

    def install
      bin.install "runpodctl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/runpod/runpodctl/releases/download/v1.14.3/runpodctl_1.14.3_linux_amd64.tar.gz"
      sha256 "8c1ed021dc531b3d51a3dc760a900c923cd05d907c229593c1d34cf3e5c98266"

      def install
        bin.install "runpodctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runpod/runpodctl/releases/download/v1.14.3/runpodctl_1.14.3_linux_arm64.tar.gz"
      sha256 "1fd855f7ba89eb2cdf0ea3ea65c4ceff4275f10e835b8f83390372b6f3e5d799"

      def install
        bin.install "runpodctl"
      end
    end
  end
end
