# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runpodctl < Formula
  desc ""
  homepage "https://github.com/runpod/runpodctl"
  version "1.14.2"

  on_macos do
    url "https://github.com/runpod/runpodctl/releases/download/v1.14.2/runpodctl_1.14.2_darwin_all.tar.gz"
    sha256 "17d5dd8893dd408cbf1af6974667a82dade97d723385770f3ff23a5214812b6f"

    def install
      bin.install "runpodctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runpod/runpodctl/releases/download/v1.14.2/runpodctl_1.14.2_linux_arm64.tar.gz"
      sha256 "e7323180b311a89e2512a874dd7ec8e17b235a704b15cf0bab54b169d940502d"

      def install
        bin.install "runpodctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runpod/runpodctl/releases/download/v1.14.2/runpodctl_1.14.2_linux_amd64.tar.gz"
      sha256 "041ebf7f69bbef1811fc45fcc35df583e80707ffc92ac502afecd15f3c2b074f"

      def install
        bin.install "runpodctl"
      end
    end
  end
end
