# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runpodctl < Formula
  desc ""
  homepage "https://github.com/runpod/runpodctl"
  version "1.14.3"

  on_macos do
    url "https://github.com/runpod/runpodctl/releases/download/v1.14.3/runpodctl_1.14.3_darwin_all.tar.gz"
    sha256 "69d6dccd91cf464c94638ae9515007a02e6ed78448fe885bb23883ce3c546e74"

    def install
      bin.install "runpodctl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/runpod/runpodctl/releases/download/v1.14.3/runpodctl_1.14.3_linux_amd64.tar.gz"
      sha256 "d26438d2798945f6de4db047547b515517f38fa145e9a66c71232a1a520facd8"

      def install
        bin.install "runpodctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runpod/runpodctl/releases/download/v1.14.3/runpodctl_1.14.3_linux_arm64.tar.gz"
      sha256 "b57e7379e6d9debe701c1d1efdc92cfc108e7ae47250ef65f4d859d10cc215ee"

      def install
        bin.install "runpodctl"
      end
    end
  end
end
